title: CV Papers Daily
description: Automatically Update CV Papers Daily using Github Actions
show_downloads: false
theme: jekyll-theme-cayman

#remote_theme: pages-themes/slate@v0.2.0
#plugins:
#- jekyll-remote-theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
